CREATE TABLE CLIENTE(
    Nit INT(4) NOT NULL,
    Nombre VARCHAR(40) NOT NULL
);
CREATE TABLE MEDICAMENTO(
    Id_med INT(4) NOT NULL,
    Nombre VARCHAR(40),
    C_comp FLOAT(4),
    C_vent FLOAT(4),
    Venc DATE NOT NULL
);
CREATE TABLE COMPRA(
    Id_med INT(4) NOT NULL,
    Nit INT(4) NOT NULL,
    Id_med INT(4) NOT NULL,
    Saldo  FLOAT(4) NOT NULL,
    Fecha DATE NOT NULL
);
CREATE TABLE SUCURSAL(
    Id_suc INT(4) NOT NULL,
    Nombre VARCHAR(40) NOT NULL,
    Telf INT(4) NOT NULL,
    Dir VARCHAR(50) NOT NULL
);
CREATE TABLE ALMACEN(
    Id_suc INT(4) NOT NULL,
    Id_med INT(4) NOT NULL,
    Ubic VARCHAR(10) NOT NULL,
    Cant_disp INT(4) NOT NULL
);
CREATE TABLE PROVEDOR(
    Id_pro INT(4) NOT NULL,
    Nombre VARCHAR(40) NOT NULL,
    Telf INT(4) NOT NULL,
    Dir VARCHAR(50) NOT NULL
);
CREATE TABLE PEDIDO(
    Id_ped INT(4) NOT NULL,
    Id_pro INT(4) NOT NULL,
    Id_suc INT(4) NOT NULL,
    Fecha_ped DATE NOT NULL
);
CREATE TABLE LOTE(
    Id_lot INT(4) NOT NULL,
    Id_ped INT(4) NOT NULL,
    Id_med INT(4) NOT NULL,
    Costo FLOAT(4) NOT NULL
);
ALTER TABLE CLIENTE
ADD CONSTRAINT PK_CLIENTE
PRIMARY KEY (nit);
ALTER TABLE MEDICAMENTO
ADD CONSTRAINT PK_MEDICAMENTO
PRIMARY KEY (id_med);
ALTER TABLE COMPRA
ADD CONSTRAINT PK_COMPRA
PRIMARY KEY (nit);

ALTER TABLE COMPRA
ADD CONSTRAINT FK_COMPRA_CLIENTE
FOREIGN KEY (nit)
REFERENCES CLIENTE(nit);

ALTER TABLE COMPRA
ADD CONSTRAINT FK_COMPRA_MEDICAMENTO
FOREIGN KEY (id_med)
REFERENCES MEDICAMENTO(id_med);
ALTER TABLE SUCURSAL
ADD CONSTRAINT PK_SUCURSAL
PRIMARY KEY (id_suc);
ALTER TABLE ALMACEN
ADD CONSTRAINT PK_ALMACEN
PRIMARY KEY (id_suc, id_med);

ALTER TABLE ALMACEN
ADD CONSTRAINT FK_ALMACEN_SUCURSAL
FOREIGN KEY (Id_suc)
REFERENCES SUCURSAL(id_suc);

ALTER TABLE ALMACEN
ADD CONSTRAINT FK_ALMACEN_MEDICAMENTO
FOREIGN KEY (id_med)
REFERENCES MEDICAMENTO(id_med);
ALTER TABLE PROVEDOR
ADD CONSTRAINT PK_PROVEDOR
PRIMARY KEY (id_pro);
ALTER TABLE PEDIDO
ADD CONSTRAINT PK_PEDIDO
PRIMARY KEY (id_ped);

ALTER TABLE PEDIDO
ADD CONSTRAINT FK_PEDIDO_PROVEDOR
FOREIGN KEY (Id_pro)
REFERENCES PROVEDOR(id_pro);

ALTER TABLE PEDIDO
ADD CONSTRAINT FK_PEDIDO_SUCURSAL
FOREIGN KEY (Id_suc)
REFERENCES SUCURSAL(id_suc);
ALTER TABLE LOTE
ADD CONSTRAINT PK_LOTE
PRIMARY KEY (id_lot);

ALTER TABLE LOTE
ADD CONSTRAINT FK_LOTE_PEDIDO 
FOREIGN KEY (Id_ped)
REFERENCES PEDIDO(id_ped);

ALTER TABLE LOTE
ADD CONSTRAINT FK_LOTE_MEDICAMENTO
FOREIGN KEY (Id_med)
REFERENCES MEDICAMENTO(id_med);
